### ISSUE TITLE
Create Contributing MD file

### ISSUE THREAD

**Issue by danitseitlin** [BeamMP/BeamMP#100]
Hi, I've seen some issues I'm interested in fixing, I'd like see a contributing MD file for me to able to sync into the project quickly.

**Comment by Starystars67** [comment]
Hi there, I will get this added asap for you! 
Thank you for your interest in the project!

**Comment by danitseitlin** [comment]
@Starystars67 Cool thanks. Make sure it includes a bit how things work here. I have a good friend who loves the servers, and I'd love to be able to maintain it for him.

**Comment by Starystars67** [comment]
Hello @danitseitlin this should now be rectified for you. Any questions please feel free to contact one of the devs in our discord for a more personal conversation or open another issue. 👍
