### ISSUE TITLE
Add BeamMP Server CLI

### ISSUE THREAD

**Issue by danitseitlin** [BeamMP/BeamMP#113]
Add ability to control the Server via CLI:
1. restart: restarting the server, which will reload the configs
2. stop / start: Basics to stop and start a server
3. reload: Reloading the server config changes

**Comment by lionkor** [comment]
Hello,
I'm one of the Server developers. The server has its own repository on GitHub: https://github.com/BeamMP/BeamMP-Server

You can use the server console to do all this.

A way to do it from a web-interface is on the roadmap.

**Comment by danitseitlin** [comment]
Where can I see a list? plus where can I integrate with it exactly? @lionkor

**Comment by Starystars67** [comment]
Can we close this issue now and any other comments related to it moved to an issue on the server repository please/
