### ISSUE TITLE
Launcher doesn't show multiplayer tile since game update 0.22

### ISSUE THREAD

**Issue by legraphista** [BeamMP/BeamMP#115]
Until the latest update, everything was working fine 
but after the update, the multiplayer doesn't show up anymore 

I've tried to remove & reinstall it but had the same result

Here's a demo https://www.youtube.com/watch?v=0a6PqTdT2uo

**Comment by 20dka** [comment]
Hey, just go into Repository and enable `multiplayerbeammp`, then restart your game.
The BeamNG.drive launcher disables all mods when updating, and this includes BeamMP if you had it on an older version

**Comment by Starystars67** [comment]
@legraphista Did what @20dka suggest solve your issue? If so can we close this issue? Thanks

**Comment by legraphista** [comment]
Hi, sorry for the holdup
I'll test the suggestion right after my work hours and come back to close the issue if it's resolved.

**Comment by legraphista** [comment]
Yes, it appears that the mod was indeed disabled. 
Thanks for the pointers :)
![image](https://user-images.githubusercontent.com/962643/114230042-4f961980-9981-11eb-956c-573759ebdfcf.png)

Any way in which it can be re-enabled if found disabled? It was pretty confusing not having it there after the update & a re-install of BeamMP

**Comment by Starystars67** [comment]
Unfortunately this is a game issue not us. On a plus note once you enable it (for this version) it should stay enabled. Though it disables on each update is seems :/ sorry. We are trying to find a fix to force it to re-enable though.

**Comment by legraphista** [comment]
I wonder where beamNG keeps its mods metadata to know which one is enabled and which one is disabled

**Comment by Starystars67** [comment]
They are kept inside the db.json. I hope this helps :)

**Comment by legraphista** [comment]
Is the `db.json` file in the game files or in %appdata%? I'm searching for it and can't find it, or is Windows just being Windows...

**Comment by 20dka** [comment]
yes its in your userfolder/mods directory
