### ISSUE TITLE
[Question] How do  remove beammp i already explained my problem 

### ISSUE THREAD

**Issue by HONEYMUSTAAAAARD** [BeamMP/BeamMP#118]
Have you checked the relevant area on our Forum / Discord / Wiki? **Yes** / **No**

Describe your question in as much detail as possible below please: now i want to play normal beammp but i cant cause everytime i open it beammp showes up i already know about opening safe file but i cant play with mods and i already went to apps and deleted it but its like a zombie or smthing

**Comment by Starystars67** [comment]
Im sorry but I am not sure what exactly you are asking here?

Please can you also use the the issue format that we have provided in future otherwise we will only ask you them again.

**Comment by Starystars67** [comment]
Given the lack of update and reply on this matter I am closing it. Please comment back on here if you did not manage to resolve the issue.
