### ISSUE TITLE
[Bug] BeamMP reports proton version of BeamNG as cracked

### ISSUE THREAD

**Issue by Sacha-Ringenbach** [BeamMP/BeamMP#128]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Running BeamMP with proton 5.0 and # WINEPREFIX=$PWD winetricks vcrun2019 , BeamMP detects the game as cracked

**To Reproduce**
1. Install Beamng using proton experimental on any linux platform 
2. Manually install BeamMP using : 
cd $HOME/.steam/steamapps/compatdata/284160
STEAM_COMPAT_DATA_PATH=/mnt/Games/Games/SteamLibraryLinux/steamapps/compatdata/284160 WINEPREFIX=$PWD  \
        /home/user/.steam/root/steamapps/common/Proton\ 5.0/proton run \
        ./drive_c/users/steamuser/Download/BeamMP_installer.exe
3. run the executable of beamp using the same method as above
4. The executable reports beamng as a cracked copy.

**Expected behavior**
I expect BeamMP to start the installation as my BeamNG install is a legitimate one.

**Desktop : **
 - OS Archlinux kernel 5.12.12

**Comment by Anonymous-275** [comment]
closed without a reason, flagging as invalid and assuming it did work.
