### ISSUE TITLE
[Bug] Player Models Don't Despawn

### ISSUE THREAD

**Issue by MeowMC** [BeamMP/BeamMP#129]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Title says it.

**To Reproduce**
1. Have someone else get out of a vehicle so that their playermodel spawns.
2. Have that same person get back into a vehicle,
3. See that playermodel does not despawn when they enter a vehicle.

**Expected behavior**
The expected behavior is that the playermodel despawns when they enter a vehicle.

**Desktop (please complete the following information):**
 - OS + Version: Windows 10

**Comment by Starystars67** [comment]
Hello @MeowMC , I have been able to confirm the issue you have raised. I will be spending some time to attempt to find a solution to resolve the issue. Thank you for reporting.

**Comment by MeowMC** [comment]
👍🏻

**Comment by MeowMC** [comment]
Also: This causes the teleportation system to cause you to teleport to their playermodel which has not despawned- Instead of teleporting to the location of their vehicle.

**Comment by Starystars67** [comment]
Just to update this, a couple of members of the team found that BeamNG have changed how the player works now. As such this is making things more complex. We are still working on it though.

**Comment by stefan750** [comment]
Hi @MeowMC can you (or someone else) confirm if this issue is still present? It should have been fixed already by #133. Thanks!

**Comment by MeowMC** [comment]
Let me go check

**Comment by MeowMC** [comment]
Unfortunately I have no one to play with currently, so I will close this issue and re open it if the issue is still present next time I play, that sound good?

**Comment by stefan750** [comment]
Yes sounds good, I wasn't able to reproduce the issue anymore during my own testing.
The only way to leave snowmen behind is if you switch to another vehicle using TAB instead of entering it, but it acts the same way in singleplayer so I will leave that as the intended behaviour for now, unless it causes other issues.

**Comment by MeowMC** [comment]
Alrighty
