### ISSUE TITLE
[Bug] Triple monitor render mode, nametags don't display on center monitor

### ISSUE THREAD

**Issue by ShadowFrost3** [BeamMP/BeamMP#137]
Name tags do not display on the center monitor when the experimental multi monitor render mode is enabled. 

Enable the multi-monitor render mode and labels and watch as they appear on the outer monitors but do not appear on the inner monitor.

**Comment by 20dka** [comment]
At first this sounds like a BeamNG bug, but I'll have to check this out in-game

**Comment by ShadowFrost3** [comment]
If it is, I'll pass it over to them.

**Comment by Starystars67** [comment]
@20dka any update on this?

**Comment by 20dka** [comment]
Sorry for the late reply, I can confirm this is a BeamNG bug, as it happens with the Nodegrabber too
![image](https://user-images.githubusercontent.com/13372364/126220154-59ab9e56-4c70-4ff5-8d04-1aaa40f5609d.png)

**Comment by Starystars67** [comment]
Closing due to being a game issue rather than a BeamMP issue.
