### ISSUE TITLE
[Bug] Unable to login when having the "^" character in your password

### ISSUE THREAD

**Issue by dutchkiller2000** [BeamMP/BeamMP#139]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
When you try to login ingame with a password containing the special character "^". You'll get an the following error in the console:
Unexpected token ^ in JSON at position 62.
And then in game I get. Invalid answer from authentication servers, please try again later.

The password had been generated by a password manager.
It also contains other special characters like "{".

Is this maybe a security flaw?? I dont realy know. Not in my alley.

**To Reproduce**
1. Change your password to one containing the character or create a new account.
2. Try to login ingame with that account.
3. See error.

**Expected behavior**
That the server can process those characters just fine and let me login.

**Screenshots**
[Console error](https://cdn.discordapp.com/attachments/665263790673231882/867789755139620864/unknown.png)

**Desktop (please complete the following information):**
 - Windows 10 Home 10.0.19042 build 19042

**Additional context**
None

**Comment by Starystars67** [comment]
Hi @dutchkiller2000 , Nice find!

My first question in relation to this is can you confirm if your password contains any of the following characters?
`Backslash, Tick, Single or Double Quote mark`
A simple yes or no shall suffice unless you wish to outline which specifically.

Kind regards

**Comment by dutchkiller2000** [comment]
> 
> 
> Hi @dutchkiller2000 , Nice find!
> 
> My first question in relation to this is can you confirm if your password contains any of the following characters?
> `Backslash, Tick, Single or Double Quote mark`
> A simple yes or no shall suffice unless you wish to outline which specifically.
> 
> Kind regards

Hi,
My password was exactly `6odumE(]KJ{BKw_^UCo"^bcK(!qEOp`

I have a new password by now :P

So that contains the following characters"
'('
']'
'{'
'_'
'^'
'"'
'!'

**Comment by Starystars67** [comment]
Hey, Thank you for getting back to me!
So as I had suspected there is a character in your password that would have broken the JSON string causing it to have issues during parsing.

As I mentioned earlier, Nice catch!

I will aim to get a fix out asap for this. Thank you!
