### ISSUE TITLE
[Bug] BeamMP disconnects users on low-end systems

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP#146]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
On low-end systems, running BeamMP, the Launcher disconnects and then successively and rapidly attempts to reconnect to the game, failing to do so properly.

**To Reproduce**
1. Have a low-end system or lower CPU affinity of the BeamNG.drive.x64.exe process
2. Join a high-pop server
3. Spawn / respawn cars

**Expected behavior**
Not disconnect from the launcher.

**Screenshots**
See attachments:
![2021-09-15_15-24](https://user-images.githubusercontent.com/29932116/133441541-c3209988-db71-48e1-8855-5ccb16637716.png)

**Desktop (please complete the following information):**
 - Windows 10

**Comment by Starystars67** [comment]
See PR #145 .
