### ISSUE TITLE
`master` usage is unclear

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP#161]
Currently, the use of `master` is unclear. 

The latest releases were from `development`. I suggest we either make `development` the default branch or merge `development` into `master` as part of a release action. 

This would involve a PR from `development` to `master` as the final release-step, which is kinda beautiful and allows for an overview over all commits and changes in that release (as a delta from the last). This makes writing the change log easier, too!

I assigned Titch and Deer as you guys are the most active currently and probably have opinions on it, but anyone else's comments are of course welcome :)

**Comment by Starystars67** [comment]
> ... or merge development into master as part of a release action.

This was supposed to be what happens though it seems to have been missed or forgotten.
I wonder if we could maybe automate this somehow to ensure that is is not missed in the future, Thoughts?

**Comment by Starystars67** [comment]
@20dka or @lionkor could you push the latest release into master based on the tags and releases please?
This at least gets master up to date as it should be. Then we can look to close this.

**Comment by lionkor** [comment]
Will do. Also note that tag 4.1.2 is missing the `v` prefix

**Comment by lionkor** [comment]
In the future it's best if we merge `development` into `master` and then tag on `master`.

**Comment by Starystars67** [comment]
Noted @lionkor , Thank you.

**Comment by lionkor** [comment]
It's still not used the way it should be, but alas
