### ISSUE TITLE
[Bug] Failed login even though it was successful

### ISSUE THREAD

**Issue by Starystars67** [BeamMP/BeamMP#173]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
When trying to login or play as guest the interface does not load correctly. It presents the user with a login error even though they did login correctly (assuming they used the correct details). Going back to the main menu and then loading MP works.

**Comment by snepsnepsnep** [comment]
I have experienced that bug on my end too, doesn't show any errors in the UI, pressing the play button for guest again will just keep creating new guests.¸
Logout button too.
All of them met with errors in the console like:
Error: Cannot transition to abstract state 'menu.multiplayer'

**Comment by snepsnepsnep** [comment]
https://github.com/BeamMP/BeamMP/pull/174 addresses these issues

**Comment by snepsnepsnep** [comment]
Update fixing that was pushed public, issue can be closed.
