### ISSUE TITLE
[Bug] Quit button doesn't quit/exit to menu, does not allow future server sessions (BeamNG .24.01, BeamMP 4.x)

### ISSUE THREAD

**Issue by JamminR** [BeamMP/BeamMP#176]
Since NG .24.01 + BeamMP 4.(?) - 
The Quit button does not take players back to the main menu, and joining future servers fails.
NG acts as though still running game in freeplay. 
(can still drive around, just no other players/not connected)
Once you hit ESC, Go to main menu, you can create single player sessions, but not any other MP game sessions.
Attempting to select multiplayer, select a new server, for a split second it acts as though it will connect, then, you go back to the server list again. Hitting ESC clears the server list and places your GUI back at the point you hit quit from the previous server (unless you'd driven around aka freeplay)
Client has to physically quit BeamNG, wait for MP launcher to quit, then restart launcher.

Dec 31 2021 additional info.
BeamMP 4.2.3 - I've noticed that if I press Quit button, wait 5-10 secs, press Quit again if the mode hasn't switched to (apparent) free play, I'll get an hourglass mouse symbol (Win10) - if i press 2-3 more times while that hour glass is showing, the game will occasionally (but not consistently) go to the 'loading UI' black screen, then load the main game menu.
If the main menu loads, we can then successfully start another MP session from server list without needing to exit game entirely.

Jan 5 2022
After one of the above mentioned 'press quit several times' attempts - BeamMP reported it had lost connection to the launcher.
Pressing "connect" did re-connect to the launcher, but I was still unable to start another server connection, ending up with previous issue (back to server list)
This text appeared launcher.
```[5/1/2022 23:20:37] [INFO] Checking Resources...
[5/1/2022 23:20:37] [INFO] Syncing...
[5/1/2022 23:20:40] [WARN] Failed to close socket!
[5/1/2022 23:20:40] [INFO] Connection Terminated!
```
The text in screenshot appeared in game as mentioned.
![image](https://user-images.githubusercontent.com/3392170/148328149-9f6e415a-afb2-4f6e-899e-1b221485e9a4.png)

Jan 11 2022
More info - was kicked from a server. (Timed restarts I'm pretty sure, seems to happen same time for me for this server)
Though normally BeamNG seems to enter freeplay mode after a kick (like this bug overall), this time, though my screen had dark overlay, all the GUI options seemed as though I was still connected. (Sorry, didn't think to look to see if my ping was changing)
After clicking 'return to menu' (which doesn't), and clicking 'quit' 5-10 times every 2-3 seconds, I was able to go to main menu. 
The following was in launcher console, kick was at 17:44. The 1.25 min later was likely after i'd pressed Quit a few times.
```
[11/1/2022 17:02:50] [INFO] Syncing...
[11/1/2022 17:03:32] [INFO] Done!
[11/1/2022 17:44:58] [WARN] Failed to close socket!
[11/1/2022 17:46:00] [WARN] Connection still alive terminating
[11/1/2022 17:46:00] [WARN] Failed to close socket!
[11/1/2022 17:46:00] [WARN] Failed to close socket!
[11/1/2022 17:46:00] [WARN] Failed to close socket!
[11/1/2022 17:46:00] [WARN] Game Reconnecting...
[11/1/2022 17:46:00] [INFO] Connection Terminated!
[11/1/2022 17:46:00] [INFO] Game Connected!
[11/1/2022 17:46:06] [WARN] Game Reconnecting...
[11/1/2022 17:46:07] [INFO] Game Connected!
[11/1/2022 17:46:08] [WARN] Game Reconnecting...
[11/1/2022 17:46:08] [INFO] Game Connected!
[11/1/2022 17:46:08] [WARN] Game Reconnecting...
[11/1/2022 17:46:08] [INFO] Game Connected!
[11/1/2022 17:46:08] [WARN] Game Reconnecting...
[11/1/2022 17:46:08] [INFO] Game Connected!
[11/1/2022 17:46:08] [WARN] Game Reconnecting...
[11/1/2022 17:46:08] [INFO] Game Connected!
[11/1/2022 17:46:08] [WARN] Game Reconnecting...
[11/1/2022 17:46:08] [INFO] Game Connected!
```

_Originally posted by @JamminR in https://github.com/BeamMP/BeamMP/issues/166#issuecomment-991962676_

**Comment by JamminR** [comment]
Server join issue also mentioned in forums.
https://forum.beammp.com/t/i-cant-join-other-servers-after-i-am-in-one/172283

**Comment by Starystars67** [comment]
Hi JamminR, Thank you for the report. We are looking into this issue at the moment. I expect to get a fix and patch rolled out sometime this week.

**Comment by JamminR** [comment]
Since about ~24 hours ago, your changes seem to have helped with this.
Still not played enough to determine if fixed 100%.

**Comment by JamminR** [comment]
This seems to have broken again with BeamMP 4.2.3 and BeamNG alpha 0.24.0.2

**Comment by JamminR** [comment]
After BeamNG updated to .24.1 - issue still exists.
I also saw, once, a BeamMP error indicating that the mod had lost connection to the launcher. After trying to connect to another server to get a screenshot (because I didn't think to first time), it didn't give the error, but instead went to server list as originally mentioned in first post of bug.

**Comment by Starystars67** [comment]
Hi @JamminR Yeah they really have played with the UI of the game and it has introduced lots of bugs here and there.

At the moment I am working on making it so that you can change servers from the menu that they have now added (instead of what used to be a case of it returning you to the main menu).

It looks like we will have to do quite some work to get this working correctly but I am trying to get this done none the less.

Thank you for keeping on top of this issue and reporting back with info on it. It is appreciated!

**Comment by JamminR** [comment]
I'll help report when I can - I don't expect immediate fixes, especially when the original game devs keep changing stuff.
I'm QA/PR with a Gmod dev group and know the pain. Keep up the great work team BeamMP.

**Comment by JamminR** [comment]
Updated original bug posting with something I noticed.
(and hope everyone here has a great start to the new year)

**Comment by Starystars67** [comment]
I will be addressing this today hopefully. Thank you for the update.

**Comment by JamminR** [comment]
More update. (if you want me to stop - just say - i'll give info as i notice)

**Comment by Starystars67** [comment]
Hey JamminR, No you're good. I am still investigating this one and trying to find a fix for it.

**Comment by JamminR** [comment]
More info / oddity being kicked from a server. (which is just a forced server quit from opposite side, right? :D )

**Comment by Starystars67** [comment]
> More info / oddity being kicked from a server. (which is just a forced server quit from opposite side, right? :D )

This is correct. My investigations so far lead me to believe that the issue sits somewhere in the lua reload and the quitting of the game. I am currently experimenting with trying to trigger the reload AFTER the return to the main menu but this is a little more difficult.

**Comment by EvanMulawski** [comment]
Just found this by accident. Calling `MPCoreNetwork.loadLevel` will end up terminating the MP session and returning the game to a good state. Joining a MP session afterward works fine. Not sure why (yet) but may help your investigation.

**Comment by lionkor** [comment]
is this still happening?

**Comment by JamminR** [comment]
This specific issue no longer happens. In MP games, pressing Quit button at top HUD/server info bar eventually quits to main menu. It seems like the Main Menu HUD has to load twice before buttons become actionable/selectable, but this seems to occur automatically.
Now I just find no way to Quit non-server connected games (Freeroam/scenarios/etc) and then join a MP/server game - but, that seems meant for a new bug report. Cheers
