### ISSUE TITLE
[Bug] UI.Debug menu, normal menu doesn't load when BeamNG starts with BeamMP

### ISSUE THREAD

**Issue by JamminR** [BeamMP/BeamMP#177]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Somewhat

**Describe the bug**
When starting BeamMP 4.x with BeamNG .24.01, a UI.Debug menu appears on right side of screen, and menu doesn't load.

**To Reproduce**
1. Start latest BeamMP launcher
2. Launch BeamNG when prompted.
3. Watch for debug
4. See bad UI

**Expected behavior**
Normal NG menu should load with MP tab added, without the UI debug panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/3392170/145730704-de109136-ea3b-4287-bed6-c80bab85235f.png)

**Desktop (please complete the following information):**
 - Win 10 x64 v20h2
 - Latest BeamNG as of this post (.24.01?)
 - Latest BeamMP as of this post (4.1?)
 - Game starts in 2k resolution, borderless window, GTX 2080 Super on a 2k Asus 27inch monitor

**Additional context**
3 work-arounds work single game session to remove the panel. (Restarting launcher, it comes back)
I dare say 'most' game players would likely have no idea how to perform 2 of them.
1) Press Ctrl+U - code window opens, set element visibility to false. Close code window. UI panel disappears. Hit escape twice
2) Press Ctrl+U - code window opens, Delete entire code element portion. Close code window. UI panel disappears. Hit escape twice
and easiest for non-geek code type people in my opinion....
3) Click the 'reload' button in the panel. Screen blanks. Hit ESC twice.

**Comment by snepsnepsnep** [comment]
Thanks for the bug report.
Issue should be fixed with the latest version, can you confirm that it works for you too?

**Comment by JamminR** [comment]
Seems this issue has gotten worse, at least in my case - I can no longer get to the Main menu of BeamNG using BeamMP Launcher, and, once BeamMP has been tried, it breaks BeamNG stand-alone too.
Upon trying loading the launcher the first time, it wiped 34 MP mods (unsure if this was intended, or due to a crash/bug on last session that i now don't remember). Once the launcher downloaded the BeamMP file and beamNG prompted to launch BeamNG, once I clicked Launch, I came to a black screen "Loading UI". 
Below that text said "Mods can slow down this process or may have broken the game, ([click here for help](https://documentation.beamng.com/support/troubleshooting/common_exit_codes/uiloading/))
That link takes me to the BeamNG generic error 'why this may happen and things to try" page.
I had to use Alt-F4 to end the program (i'm on win10 20h2).
Tried a second time - same results.
I then tried loading BeamNG without using BeamMP launcher - it at least gets as far as the 'photosensitivity warning' screen, then fails with the loading UI screen again.
Upon next launch, i attempted the (non-deep) clear cache. It did it's clean and hash, and completed.
I tried launching BeamNG stand alone again (no BeamMP launcher) - beamNG loaded fine this time.
I exited the game.
Tried loading BeamMP - back to loading UI.

Good luck. I'll continue trying/reporting as I have time when you ask.

**Comment by snepsnepsnep** [comment]
Make sure you've updated the game to the latest version (0.24.0.2) otherwise what you're describing will happen.

**Comment by JamminR** [comment]
Wow.
Launcher didn't tell me the 'game is X than recommended' so, even though I'm a detail oriented geek, I never even considered seeing if there was an update.
My apologies. I return you back to your normally scheduled programming. Menu seems to be working now.
![Sheepish](https://user-images.githubusercontent.com/3392170/146625778-4cb4666e-26a3-4af6-924f-db414d79bb95.gif)

**Comment by snepsnepsnep** [comment]
Sorry about that, forwarded it to the team but I'm not the one that can do the signing and release of the launcher.
Closing the issue.
