### ISSUE TITLE
[Bug] Vehicles will sometimes not spawn when joining a server

### ISSUE THREAD

**Issue by snepsnepsnep** [BeamMP/BeamMP#181]
Issue seems to be rare but it has been reported by a few people, in one case seemingly being fixed by updating game (might have been unrelated)
It might be related to the recently changed checkIfVehiclenameValid() function in MPVehicleGE due to a game update and game function change.

Currently more info is necessary to look into the bug.

**Comment by lionkor** [comment]
I've seen this multiple times, with the latest BeamMP version they will only see the black orbs, not the vehicles, upon joining.

**Comment by Starystars67** [comment]
Same here, @20dka could you look into this please as you were the last one to touch this aspect?

**Comment by lionkor** [comment]
Is this still happening?

**Comment by snepsnepsnep** [comment]
Likely fixed in https://github.com/BeamMP/BeamMP/pull/265
