### ISSUE TITLE
[Bug] Server list Favorite tab issue - duplicate rows when server offline

### ISSUE THREAD

**Issue by JamminR** [BeamMP/BeamMP#182]
When in Favorites tab of server list, if a Favorite server is offline, it will fill the 'last' entry of the favorites list for (hundreds?) of rows, with various player amounts and FPS amounts. This issue has existed for several versions (I started BeamMP ~Jun 2021 - noticed not long after that)

**To Reproduce**
1. Add an operational server to favorites
2. Shut down server (if you own) or wait until server goes offline.
3. When in Favorite server view, watch pages of rows of offline server with various player and FPS numbers.

**Expected behavior**
A single row indicating 'offline'

**Screenshots**
![image](https://user-images.githubusercontent.com/3392170/146630240-10addb70-f325-4d30-bb7d-11193a2a5d3a.png)

**Desktop (please complete the following information):**
 - Win10 20H2 x64. Multiple BeamMP (and BeamNG) versions since Jun 6 2021.

**Comment by JamminR** [comment]
I checked/closed 2 other bug reports I had - one regarding Add Favorites not working.
Give me a bit longer to determine if this issue still occurs - i just now went back into Favorites for the first time in many months and had to clean out what I believe were old duplicates. None of my current favorites have been offline yet for me to test.

**Comment by JamminR** [comment]
Sorry so long, but my Favorites list apparently had stable servers -
This issue still occurs.
![image](https://user-images.githubusercontent.com/3392170/187053676-8cf41885-abce-414e-8b04-8e1e2428bc06.png)

**Comment by Starystars67** [comment]
Hello, sorry for the huge delay on this one. I am pretty sure that this issue is now resolved in the current version (though I cannot find the commit. :/ 

I will close this issue for now but please comment back if it is not and I will dig into it again.
