### ISSUE TITLE
[Bug] Server list view - Add Favorite button not working

### ISSUE THREAD

**Issue by JamminR** [BeamMP/BeamMP#183]
Since BeamNG .24 and it's matching updated BeamMP version (4.2?), the "Add Favorite" button does not add to the Favorites tab server listing. (Remove Favorite still works)

1. Go to main Server listing in BeamMP (issue exists in "Recent" tab also)
2. Select a server.
3. Click it's "Add Favorite" button.
4. Though the server info will collapse as though server was added to favorites, go to Favorites - no server added.

**Expected behavior**
Favorites list will show the server that "Add Favorite" button was clicked.

**Desktop (please complete the following information):**
Win10 20H2, BeamMP 4.2.3, BeamNG .0.24.0.2

**Comment by lionkor** [comment]
Is this still happening?

**Comment by JamminR** [comment]
Add Favorite button is now working
