### ISSUE TITLE
Manual physics manipulation

### ISSUE THREAD

**Issue by 1Euro7Cent** [BeamMP/BeamMP#184]
Have you checked the relevant area on our Forum / Discord / Wiki? **Yes** 

Describe your question in as much detail as possible below please:

My friend and I are playing multiplayer, and we found the physics manipulation tool.(hold CTRL) But if I change something on my friend's car they don't see that. Is that intended or a bug. If this is intended please make that configurable in the config.

**Comment by 20dka** [comment]
Hey, the BeamMP mod does not sync nodes, only vehicle positions, velocities, and inputs.
