### ISSUE TITLE
Mod Loading issue

### ISSUE THREAD

**Issue by Starystars67** [BeamMP/BeamMP#193]
Author: 10K Racing

Message:
I like others have been having the problem of not getting into servers. Mine to be more specific. It would just stop loading and go no further. Been happening for weeks and getting worse. I tried the experimental loading option which showed me it was getting stuck on the same mod. Then finally figured out it was getting stuck on the mods with spaces in the name. Changed those to underscores... BAM i can get into my server.  Though if i uncheck the experimental mod loading it still gets stuck and i never get in. Obviously not everyone has this problem. My brother could get in the server, but not me. So maybe this helps someone or maybe gives the Devs some info.  Rock On !

**Comment by WiserTixx** [comment]
This seems to have been resolved. Please re-open if it still happens.
