### ISSUE TITLE
[Bug] Player List error when game menu is open

### ISSUE THREAD

**Issue by EvanMulawski** [BeamMP/BeamMP#194]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
JS error logged to console regarding the Player List app. (Just something I noticed when working on a mod.)
```
CEF.MainGEUI#local://local/ui/modules/apps/BeamMP-PlayerList/app.js:130
Uncaught TypeError: Cannot read property 'rows' of null
```

Cause (?):
https://github.com/BeamMP/BeamMP/blob/100fd5bec259db8047fe9bb88f55b2881dd2076d/ui/modules/apps/BeamMP-PlayerList/app.js#L80
`playersList` is `null` because the node does not exist when the menu is open.

Solution (?):
Add a null check and return if `playersList` is `null`.

**To Reproduce**
1. Join a server
2. Use a UI with the Player List app added
3. Open the game menu (Esc)
4. JS error is logged to the console every second while the menu is open

**Expected behavior**
No error occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/1044791/149639138-0c1198ef-4559-491b-b1bd-10a7fe4a11e5.png)

**Desktop (please complete the following information):**
 - OS + Version: Windows 10 21H1
 - BeamMP 4.2.3
 - BeamNG 0.24.1.1

**Comment by snepsnepsnep** [comment]
This has been fixed in https://github.com/BeamMP/BeamMP/pull/232
