### ISSUE TITLE
[Bug] Gamertag font size doesn't follow UI Maximum Resolution setting

### ISSUE THREAD

**Issue by ericutah** [BeamMP/BeamMP#198]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
The font in the username shown above player vehicles doesn't appear to use the UI Maximum Resolution setting resulting in tiny fonts displayed when high resolution displays are used.

**To Reproduce**
1. In gameplay (not the first main screen), select Options -> User Interface (advanced), and select a UI Maximum Resolution (eg 1920x1080 for a 4k display, or 1280x720 on an HD display).
2. Note that all UI menu elements now are shown in the correct virtual resolution, but gamertags fonts above player vehicles are displayed as smaller, native DPI.

**Expected behavior**
Gamertag font sizes should match the configured UI resolution setting.

**Screenshots**
![beam](https://user-images.githubusercontent.com/26935470/151059088-b3e7f61f-d324-4b59-8f21-3974a0c9fde8.jpg)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
None

**Comment by snepsnepsnep** [comment]
We use the `debugDrawer:drawTextAdvanced()` function to draw the tags, and it does not follow the UI resolution scaling.
The function doesn't appear to support any scaling arguments either.
