### ISSUE TITLE
[Feature Request] Persist server-list search settings

### ISSUE THREAD

**Issue by lionkor** [BeamMP/BeamMP#201]
**Is your feature request related to a problem? Please describe.**
When i look for servers, i always set mods to 50 or 100 mb max, and select exclude empty or full. I have to do this every time, and it's annoying.

**Describe the solution you'd like**
The settings should per persisted, e.g. in a file, and loaded when I open the server list again. It should also be apparent that I'm looking at a filtered view, so that I don't forget that filters are set.

Maybe not all filters should be persisted, but mod size and full/empty should be.

**Additional context**

Since BeamMP-Launcher v3, the IPC should make this easier. The game can simply serialize it into json, the launcher can save that on disk.

**Comment by Starystars67** [comment]
@20dka could you adjust the UI to save these parameters to the cache?
I realise that they would be cleared on update of game or clear of cache however that could be seen to be a better thing?

**Comment by 20dka** [comment]
sure I can look into this. we could also save them to the persistent mp config so they dont get cleared on cache regeneration

**Comment by Starystars67** [comment]
This was resolved in #278 .
