### ISSUE TITLE
[Bug] Sound Effect bug - lag - unresponsive client after extended session time

### ISSUE THREAD

**Issue by JamminR** [BeamMP/BeamMP#205]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
After playing on a server for 'some time', the game starts lagging, and eventually framerate and game response gets so choppy that player must quit game. 
I noticed that once this starts, the below error appears repeatedly in console, forever filling console, even apparently after disconnecting from server (as though it may be queued hundreds of times)
Error in console is "SFXFMODDevice::update - Failed to update event system! An invalid object handle was used."

This seems to occur after at least 45 minutes on busy (10+ plus people) servers, but I've noticed at 90 minutes on 3-5 varying.

**To Reproduce**
1. Join Server
2. Play with lots of sound effects for minimum of 45 minutes. (I tend to do drift and or do high speed turns - therefore, perhaps tire squeal?)

**Expected behavior**
Game not to start being choppy / lagging

**Screenshots**
![BeamMP_lag_after_time_sound_error](https://user-images.githubusercontent.com/3392170/152464099-3cacebf4-35aa-4071-b308-eefb940fbc7c.jpg)

**Desktop (please complete the following information):**
 - OS + Version: Win10 20H2 / Gigabyte x570 Aorus pro / Realtek soundchip i forget model
 - BeamMP latest
 - BeamNG latest as of this post
 
**Additional context**
This has happened over one to two month eight times to me playing three to four times per week.
I've attempted 4-5 times in single player without BeamMP loaded and have been unable to reproduce.

**Comment by JamminR** [comment]
I really hate to post bugs like this that are inconsistent. I tried to reproduce in non BeamMP loaded single player but have not been able to, and only once purposely looking to reproduce it in multiplayer. 
If you want any external logs files from anywhere, or have command line launcher options or in-game commands you want me to use to get more info during gameplay, I'm more than willing.

**Comment by Olrosse** [comment]
Hey, thanks for the report, this is actually not a multiplayer bug, it's to do with sounds and car resets AFAIK, so all we can really do is wait for a game update, i believe the reason it's more common in multiplayer is because of how many cars are actively in use, it's probably just as likely in single player if the scenarios where the same, i also see this bug quite often, especially when playing carp, so i also can't wait for a fix soon haha

**Comment by JamminR** [comment]
So, since this is (apparently) a BeamNG bug, should I close?
Or do 'we' BeamMP fans keep it open and monitor for BeamNG updates?

And if close, where can we officially report BeamNG bugs. I've seen Steam community discussion area/etc, but, that's just never seemed like a 'logical/clean/easy to track' place to post them.

**Comment by Anonymous-275** [comment]
https://beamng.com/game/news/announce/hotfix-0-24-1-2/

just came in :D
