### ISSUE TITLE
Realistic shifting skiping gears.

### ISSUE THREAD

**Issue by Muxoid** [BeamMP/BeamMP#80]
When shifting in realistic mode gears skip one gear. When shifting from neutral it skips to second gear and then from second to fourth gear and so on.

**Comment by 20dka** [comment]
Hey! thanks for the report. what vehicle and shifter was the observed car? what shifter mode did the other player select?

**Comment by Muxoid** [comment]
I tried a dozen cars and they all do the same I use a PS4 controller and emulate it with DS4Windows this works fine in single player mode. I was in a lobby with multiple people I am not sure what mode they were in but my friend that I was playing with was in Arcade shifting mode. To switch to realistic mode I use the "Q" shortcut.

Hope this helps, keep up the great work.

**Comment by 20dka** [comment]
it might be something related to the controller, look at this post: https://forum.beammp.com/topic/405/beamng-don-t-response-to-my-ps4-controller-while-the-beammp-mod-is-activated/6?_=1611504117402
that user is complaining about double presses, maybe thats happening to you too.

**Comment by Muxoid** [comment]
Yes, this is my problem. I turn on PS4 controller support in steam big picture mode and added the game as a non-steam game to my library. It fixed the issue.
Thanks for your help.
