### ISSUE TITLE
Launcher Says Game is Cracked

### ISSUE THREAD

**Issue by Junkob101** [BeamMP/BeamMP#93]
I have a copy of the game that is being shared by a friend over steam. 
Unfortunately, the installer seems to mistake it for a cracked version of the game.
[Screenshot of the game in my library](https://hello-this-is.indian-support.tech/xwmEeUpL)

**Comment by Starystars67** [comment]
We are working to try to find a way to make the system work with Family Share too.

**Comment by VanishedMC** [comment]
Don't know if there are any details I can provide to help with this, but I'm running Beam-MP with the game through family mode, never had any issues

**Comment by Starystars67** [comment]
@VanishedMC well this makes it a little awkward, We did allow Family share as @Anonymous-275 can confirm however there does seem to randomly be cases where it seems not to work. Though I am yet to physically see one of these cases myself. Maybe @Junkob101 can contact me on the BeamMP discord (Username is Titch) and we can take a look at it?

**Comment by Anonymous-275** [comment]
i can confirm as long as the game is playable through steam and installed by steam there shouldn't be any issues however if there is still one please contact us on discord.

**Comment by Junkob101** [comment]
> 
> 
> @VanishedMC well this makes it a little awkward, We did allow Family share as @Anonymous-275 can confirm however there does seem to randomly be cases where it seems not to work. Though I am yet to physically see one of these cases myself. Maybe @Junkob101 can contact me on the BeamMP discord (Username is Titch) and we can take a look at it?

Will do

**Comment by DonFlymoor** [comment]
I can't get BeamMP to work with the humble bundle version, and I do not want to use the steam version. I propose that we remove the drm embedded in BeamMP, as BeamNG has already made the decision to be drm free.

**Comment by Starystars67** [comment]
This should all be resolved now as of one of the minor patch updates that we did. Please comment back here if you encounter the issue still. Otherwise I am closing this issue for now as it is resolved.
