### ISSUE TITLE
Add a License File

### ISSUE THREAD

**Issue by Alfagun74** [BeamMP/BeamMP#94]
No comment needed. If you want people to work on this you need a license file.

**Comment by antoniogermano** [comment]
Here's a quick summary if you need help choosing: https://choosealicense.com

**Comment by Starystars67** [comment]
Hi there. I hope this addresses your concerns. Sorry for the delay. If all is okay please close this issue. If you have questions please feel free to comment back so we can try to come to some arrangement!
